# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name: 'LinaSelfHostedPool'  # Ensure this matches the name of your self-hosted agent pool

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  revision: $[counter(variables['minor'],1)]
  nugetVersion: '$(Major).$(revision).$(Minor)'
  nugetProjectName: 'TrainingAutomationFramework'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    vstsFeed: 'lsun0005'  # Replace with your feed name
    externalFeedCredentials: 'NuGetFeedConnection'  # Replace with your service connection name

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Create Nuget Package'
  inputs:
    command: 'pack'
    packagesToPack: '**/$(nugetProjectName).csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    arguments: '--configuration $(buildConfiguration) /p:PackageVersion=$(nugetVersion)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'lsun0005'  # Replace with your feed name
    externalFeedCredentials: 'NuGetFeedConnection'  # Replace with your service connection name

